name: chess_rl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - cudatoolkit
  - psutil
  - pip:
    - ray
    - python-chess
    - pyspiel
    - gymnasium
    - numpy
    - matplotlib
    - tensorboard
    - pyyaml
